### ISSUE TITLE
Ignore set number

### ISSUE THREAD

**Issue by lvim-tech** [nvim-telescope/telescope-project.nvim#25]
When loading **first** file, telescope-project ignore **number, cursorcolumn, cursorline**

**Comment by claidler** [comment]
@lvim-tech could you explain this issue further please?

**Comment by lvim-tech** [comment]
https://user-images.githubusercontent.com/82431193/117242567-2cef0780-ae3e-11eb-869b-79dbe2436fbf.mp4

**Comment by claidler** [comment]
@lvim-tech interesting. I use numbers and am not seeing that issue, so I'm unsure if it's related to the telescope project extension. I'll keep this open and see if there are any further reports of this.

**Comment by Conni2461** [comment]
Its a telescope issue and there are already half a dozen issues open :rofl: 
See https://github.com/nvim-telescope/telescope.nvim/issues/62 https://github.com/nvim-telescope/telescope.nvim/issues/207 https://github.com/nvim-telescope/telescope.nvim/issues/377 https://github.com/nvim-telescope/telescope.nvim/issues/678 https://github.com/nvim-telescope/telescope.nvim/issues/822 Last one has the best reproduce.

@l-kershaw What you said makes sense. Do you have an idea how to fix this issue? Because i already looked at it multiple times and i have no idea

**Comment by l-kershaw** [comment]
Ah, I probably should have checked to see if there was already an issue.
Half a dozen is a lot to miss 🤣

I'll have a look at it and see if I can come up with anything

**Comment by lvim-tech** [comment]
@l-kershaw , thanks!
