### ISSUE TITLE
base_dirs are ignored after removal

### ISSUE THREAD

**Issue by horseinthesky** [nvim-telescope/telescope-project.nvim#96]
Hello. Thank you for a nice extention.

I have the following config:
```
require("telescope").setup {
  defaults = {
    ...
  },
  extensions = {
    project = {
      base_dirs = {
        "~/dotfiles",
        "~/fzf",
        "~/neovim",
      },
    },
  },
}

require("telescope").load_extension "project"
```

First time I ran `:Telescope project` I was there three projects but after I removed them via `c-d` binding they are not shown after nvim restart anymore.

I can manually add them by cd'ing to every project dir, opening nvim add pressing `c-a`.

But how to make it respect config settings and always show every project mentioned?

**Comment by dhananjaylatkar** [comment]
It is by design (https://github.com/nvim-telescope/telescope-project.nvim/blob/master/lua/telescope/_extensions/project/actions.lua#L81=)

If you want to rebuild `telescope-projects.txt`, you can delete the file and on next restart of neovim `telescope-projects.txt` will be created using your config.

**Comment by horseinthesky** [comment]
Ah, it's in `$HOME/.local/share/nvim/telescope-projects.txt`. Ok, thank you.
